### PR TITLE
Bump duckdb and apply patch

### PR DESCRIPTION
**Pull request by carlopi**
Equivalent to https://github.com/duckdb/sqlite_scanner/pull/92, plus bumping to the extension-ci-tools workflows.

### CODE REVIEW

**Comment by carlopi** [comment]
Problem here is with extension-ci-tools, blocked on https://github.com/duckdb/extension-ci-tools/pull/19

**Comment by carlopi** [comment]
Failure is unconnected, and tied to a duckdb / extension-ci-tools problem, that I will solve in a duckdb PR.

**Comment by Mytherin** [comment]
Let's fix that first before merging this then?

**Comment by carlopi** [comment]
https://github.com/duckdb/sqlite_scanner/pull/94 it is

**Pull request closed without merging**
