### PR TITLE
CI changes for packaging duckdb-wasm AND publishing on nightly bucket

### PR DESCRIPTION
**Pull request by carlopi**
Other workflows `.github/workflows/MacOS.yml` & co still have testing infrastructure that is specific to sqlite_scanner.

For now it's a bit wasteful the duplication, but I think it's OK (eventually testing step should go also in).

Update: fixed, stuff has been unified in a single workflow.

### CODE REVIEW

**Comment by Mytherin** [comment]
Do we need to copy and paste the `[extension-upload.sh](https://github.com/duckdb/sqlite_scanner/pull/76#diff-d643cd08163ebc83fc7aa71ccc8d23704d939d8580f0423fd21b8f1530899edb)` script here? The WASM builds also seem to have a lot of code duplication. Maybe that could be isolated through a `WASM_BUILD` environment variable (e.g. `make wasm WASM_BUILD=eh`)?

**Comment by carlopi** [comment]
> Do we need to copy and paste the `extension-upload.sh` script here - can't we use the one from the main repo?

I think current setting is that repositories based on extension-template should have, at a minimum:
* a driver like `.github/workflow/MainDistributionPipeline.yml`
* a copy of `.github/workflow/_extension_deploy.yml`
* a copy of `scripts/extension-upload.sh`

We can look with @samansmink at ways to get rid of extension-upload.sh in general, but for now I think the model requires these to be duplicated. This is true for sure for the general case, but our special case we might do with less code duplication. I will come back to this.

> The WASM builds also seem to have a lot of code duplication. Maybe that could be isolated through a `WASM_BUILD` environment variable (e.g. `make wasm WASM_BUILD=eh`)?
Right, makes sense. This is modelled to the way it's in the extension-template and in duckdb/duckdb/Makefile, but should be done better.

Thanks for the feedback, will come back later after addressing it.

**Comment by carlopi** [comment]
@Mytherin: I reworked the Makefile part on duckdb-wasm, should be a bit cleaner what's reused and what's specific.

Also, mentioned by @samansmink, we could think of ways to delegate to a common CMake, but that I would move to the next iteration.

On the extra workflow and extra script, I think we have a path forward on that, should that be a blocker or this can go further while working on that on top?

**Comment by Mytherin** [comment]
I'm fine merging this for now

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
